# Development mode
dev:
  # Server configurations
  server:
    host: "localhost"
    port: 8000

  # Database path
  database: "host=localhost port=5432 user=postgres password=password dbname=oustory"

# Production mode
prod:
  # Server configurations
  server:
    host: "localhost"
    port: 8000

  # Database path
  database: "host=localhost port=5432 user=postgres password=password dbname=oustory"